source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.3'
inhibit_all_warnings!

pod 'Typhoon'
pod 'AFNetworking'
pod 'Realm'
pod 'SWRevealViewController'
pod 'Mantle'
pod 'Overcoat', :git => 'https://github.com/alesanro/Overcoat.git'
pod 'Masonry'
pod 'CocoaLumberjack'
pod 'UIScrollView-InfiniteScroll'
