source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.3'
inhibit_all_warnings!

pod 'Typhoon'
pod 'AFNetworking'
pod 'Realm'
pod 'SWRevealViewController'
pod 'Masonry'
pod 'CocoaLumberjack'
pod 'Realm+JSON'